import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import sharp from 'sharp'

test.beforeEach(async ({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('mp.onboarded','1');localStorage.setItem('mp.prefs',JSON.stringify({themeMode:'program',timezone:'America/Toronto',regionCode:'CA',broadcastRegion:'CA'}))})
})

test('a saved individual fixture survives navigation and exports through the main guide', async ({page})=>{
  await page.goto('/sports/soccer')
  await expect(page.getByRole('heading',{level:1})).toHaveText('Soccer Channel')
  await expect(page.locator('main')).not.toContainText(/host cities|48 teams|World Cup '26/)
  const toggle=page.getByRole('button',{name:/Expand details for/}).first()
  await expect(toggle).toBeVisible()
  const title=(await toggle.getAttribute('aria-label'))!.replace('Expand details for ','')
  await page.getByRole('button',{name:'Add to schedule',exact:true}).first().click()
  await page.goto('/my-schedule')
  await page.getByRole('button', { name: /Settings.*Timezone and display/ }).click()
  await page.getByRole('checkbox', { name: 'Hide finished matches' }).uncheck()
  await page.getByRole('button', { name: 'Close guide' }).click()
  await expect(page.locator('main')).toContainText(title)
  await page.getByRole('button',{name:/^Download/}).click()
  const dialog=page.getByRole('dialog',{name:'Download'})
  await expect(dialog.getByRole('button',{name:'Close guide'})).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button',{name:'Continue',exact:true})).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button',{name:'Close guide'})).toBeFocused()
  await dialog.getByRole('button',{name:'Continue',exact:true}).click()
  await dialog.getByRole('button',{name:'Continue',exact:true}).click()
  const downloaded=page.waitForEvent('download')
  await dialog.getByRole('button',{name:'Download ICS',exact:true}).click()
  const path=await (await downloaded).path()
  const content=await readFile(path!, 'utf8')
  expect(content).toContain(title)
  expect(content).toContain('BEGIN:VALARM')
  expect(content).toContain('UID:')
})

test('community fixtures use league time, edits preserve IDs, and photos have bounded uploads', async ({page})=>{
  await page.goto('/custom-leagues')
  await page.getByLabel('League name',{exact:true}).fill('Audit community league')
  await page.getByRole('button',{name:'Create league',exact:true}).click()
  await page.getByRole('link',{name:/Manage/}).click()
  await page.getByLabel('League timezone',{exact:true}).fill('Asia/Tokyo')
  await page.getByLabel('League timezone',{exact:true}).press('Tab')
  await page.getByLabel('Title',{exact:true}).fill('Community practice')
  await page.getByLabel('Date',{exact:true}).fill('2026-10-20')
  await page.getByLabel('Time',{exact:true}).fill('18:30')
  await page.getByLabel('Duration (minutes)').fill('90')
  await page.getByRole('button',{name:'Add event',exact:true}).click()
  const initial=await page.evaluate(()=>JSON.parse(localStorage.getItem('mp.customLeagues')!)[0].events[0])
  expect(initial.startsAt).toBe('2026-10-20T09:30:00.000Z')
  expect(initial.endsAt).toBe('2026-10-20T11:00:00.000Z')
  await page.getByRole('button',{name:'Edit',exact:true}).click()
  await page.getByLabel('Time',{exact:true}).fill('19:00')
  await page.getByRole('button',{name:'Save event',exact:true}).click()
  const updated=await page.evaluate(()=>JSON.parse(localStorage.getItem('mp.customLeagues')!)[0].events[0])
  expect(updated.id).toBe(initial.id)
  expect(updated.version).toBe(2)
  expect(updated.startsAt).toBe('2026-10-20T10:00:00.000Z')
  const upload=page.getByLabel('League image',{exact:true})
  await expect(upload).toBeDisabled()
  await page.getByRole('checkbox',{name:'I have permission to use and share this image.'}).first().check()
  const png=await sharp({create:{width:8,height:8,channels:4,background:'#206ba5'}}).png().toBuffer()
  await upload.setInputFiles({name:'test.png',mimeType:'image/png',buffer:png})
  await expect(page.getByText('Image saved. Originals and photo metadata are not uploaded.')).toBeVisible()
  const image=await page.evaluate(()=>JSON.parse(localStorage.getItem('mp.customLeagues')!)[0].image)
  expect(image.dataUrl.length).toBeLessThan(100000)
  expect(image.permissionConfirmed).toBe(true)
  await page.goto('/my-schedule')
  await expect(page.locator('main')).toContainText('Community practice')
})

test('calendar preview cannot issue a fake live link',async ({page})=>{
  await page.addInitScript(()=>localStorage.setItem('mp.follows',JSON.stringify([{targetType:'league',targetId:'11111111-1111-4111-8111-111111111111',intent:'watch'}])))
  await page.goto('/calendar')
  await page.getByRole('button',{name:'Create feed',exact:true}).click()
  await expect(page.getByText('Sign in to activate a live URL')).toBeVisible()
  await expect(page.getByRole('button',{name:'Copy URL',exact:true})).toBeDisabled()
  await expect(page.getByRole('button',{name:'Open webcal subscribe link',exact:true})).toBeDisabled()
})

test('DAZN stays readable in light and dark modes',async ({page})=>{
  await page.goto('/sports/soccer')
  await page.getByRole('button',{name:'Filter by UEFA Champions League',exact:true}).click()
  const badge=page.getByTitle(/(?:Check coverage|Event listing) on DAZN/).first()
  await expect(badge).toBeVisible()
  await expect(badge).toHaveCSS('color','rgb(255, 250, 240)')
  await page.getByRole('button',{name:'Switch to Broadcast Dark'}).click()
  await expect(badge).toHaveCSS('color','rgb(255, 250, 240)')
})
