import type { CSSProperties } from 'react'
import { getSport, isSecondarySport } from '../domain/sports'
import { getTheme } from '../theme/themes'
import { sportArtwork } from '../data/sportArtwork'

// Secondary ("Other Sports") tiles all share the single Other Sports icon: we don't ship per-sport
// art for them, and borrowing a primary sport's icon (rugby→football, volleyball→basketball) was
// misleading. The shared isSecondarySport rule (domain/sports.ts) keeps icon + banner uniform.

type SportAssetIconProps = {
  sportKey: string
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'channel' | 'poster' | 'hero'
  variant?: 'brush' | 'plate' | 'neon3d'
  className?: string
  label?: string
}

// Cross-naming for primary sport families and their leagues. Secondary sports are NOT listed here
// — they resolve to the Other Sports icon via SECONDARY_SPORT_KEYS below.
const aliases: Record<string, string> = {
  // Canonical sport keys (as stored in the DB / spotlight rows) → their asset filename. Without
  // these, a DB sportKey like "combat_sports" requests combat_sports.webp, which 404s.
  american_football: 'football',
  combat_sports: 'combat',
  olympic_sports: 'olympic',
  f1: 'motorsport',
  formula1: 'motorsport',
  nba: 'basketball',
  wnba: 'basketball',
  fiba: 'basketball',
  nfl: 'football',
  cfl: 'football',
  nhl: 'hockey',
  ufc: 'combat',
  pfl: 'combat',
  mma: 'combat',
  athletics: 'track',
  track_field: 'track',
  trackfield: 'track',
  olympics: 'olympic',
  community: 'custom',
}

function sportAssetKey(key: string) {
  if (isSecondarySport(key)) return 'custom'
  const sport = getSport(key)
  return aliases[sport?.badgeKey ?? key] ?? sport?.badgeKey ?? aliases[key] ?? key
}

function assetPath(key: string, variant: NonNullable<SportAssetIconProps['variant']>) {
  const assetKey = sportAssetKey(key)
  const refreshed = sportArtwork[assetKey]
  if (refreshed && variant !== 'plate') return refreshed[variant === 'brush' ? 'program' : 'broadcast'].icon
  const folder = variant === 'neon3d' ? 'neon-3d' : variant === 'plate' ? 'brushed-plates' : 'brushed-mask'
  // WebP variants are generated by scripts/optimize-images.mjs (resized to display size).
  return `/assets/sport-icons/${folder}/${assetKey}.webp`
}

export function SportAssetIcon({
  sportKey,
  size = 'md',
  variant = 'brush',
  className = '',
  label,
}: SportAssetIconProps) {
  const theme = getTheme(sportKey)
  const src = assetPath(sportKey, variant)
  const refreshed = Boolean(sportArtwork[sportAssetKey(sportKey)] && variant !== 'plate')
  const displaySize = { xs: 24, sm: 44, md: 64, lg: 86, channel: 62, poster: 148, hero: 150 }[size]
  const accessible = Boolean(label)

  if (variant !== 'brush' || sportArtwork[sportAssetKey(sportKey)]) {
    return (
      <img
        src={src}
        srcSet={refreshed ? `${src.replace('.webp', '-160.webp')} 160w, ${src} 320w` : undefined}
        sizes={refreshed ? `${displaySize}px` : undefined}
        alt={label ?? ''}
        aria-hidden={accessible ? undefined : true}
        className={`sport-asset-image sport-asset-${size} ${className}`}
        draggable={false}
        loading="lazy"
        decoding="async"
      />
    )
  }

  return (
    <span
      className={`sport-asset-icon sport-asset-${size} ${className}`}
      style={
        {
          '--sport-asset-url': `url("${src}")`,
          '--sport-asset-primary': theme.colors.primary,
          '--sport-asset-accent': theme.colors.accent,
        } as CSSProperties
      }
      role={accessible ? 'img' : undefined}
      aria-label={label}
      aria-hidden={accessible ? undefined : true}
    >
      <span className="sport-asset-glow" />
      <span className="sport-asset-core" />
      <span className="sport-asset-sheen" />
    </span>
  )
}
